[tool.poetry]
name = "four-month-calendar"
version = "0.1.0"
description = ""
authors = ["mlokos <mlokos.github@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fpdf = "^1.7.2"
Babel = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
